rules-vorobeij:
  formatting:
    active: true
    android: false
    AnnotationOnSeparateLine:
      active: true
    AnnotationSpacing:
      active: true
    ArgumentListWrapping:
      active: true
      indentSize: 4
      maxLineLength: 120
    BlockCommentInitialStarAlignment:
      active: false
    ChainWrapping:
      active: true

    CommentSpacing:
      active: true

    CommentWrapping:
      active: false
      
      indentSize: 4
    DiscouragedCommentLocation:
      active: false

    EnumEntryNameCase:
      active: true

    Filename:
      active: true
    FinalNewline:
      active: true
      
      insertFinalNewLine: true
    FunKeywordSpacing:
      active: false

    FunctionTypeReferenceSpacing:
      active: false

    ImportOrdering:
      active: true
      
      layout: '*,java.**,javax.**,kotlin.**,^'
    Indentation:
      active: true
      
      indentSize: 4
    KdocWrapping:
      active: false
      
      indentSize: 4
    MaximumLineLength:
      active: true
      maxLineLength: 120
      ignoreBackTickedIdentifier: false
    ModifierListSpacing:
      active: false

    ModifierOrdering:
      active: true

    MultiLineIfElse:
      active: true

    NoBlankLineBeforeRbrace:
      active: true

    NoBlankLinesInChainedMethodCalls:
      active: true

    NoConsecutiveBlankLines:
      active: true

    NoEmptyClassBody:
      active: true

    NoEmptyFirstLineInMethodBlock:
      active: true

    NoLineBreakAfterElse:
      active: true

    NoLineBreakBeforeAssignment:
      active: true

    NoMultipleSpaces:
      active: true

    NoSemicolons:
      active: true

    NoTrailingSpaces:
      active: true

    NoUnitReturn:
      active: true

    NoUnusedImports:
      active: true

    NoWildcardImports:
      active: true
      packagesToUseImportOnDemandProperty: 'java.util.*,kotlinx.android.synthetic.**'
    PackageName:
      active: true

    ParameterListWrapping:
      active: true
      
      maxLineLength: 120
    SpacingAroundAngleBrackets:
      active: true

    SpacingAroundColon:
      active: true

    SpacingAroundComma:
      active: true

    SpacingAroundCurly:
      active: true

    SpacingAroundDot:
      active: true

    SpacingAroundDoubleColon:
      active: true

    SpacingAroundKeyword:
      active: true

    SpacingAroundOperators:
      active: true

    SpacingAroundParens:
      active: true

    SpacingAroundRangeOperator:
      active: true

    SpacingAroundUnaryOperator:
      active: true

    SpacingBetweenDeclarationsWithAnnotations:
      active: true

    SpacingBetweenDeclarationsWithComments:
      active: true

    StringTemplate:
      active: true

    TrailingComma:
      active: false
      
      allowTrailingComma: false
      allowTrailingCommaOnCallSite: false
    TypeArgumentListSpacing:
      active: false

    UnnecessaryParenthesesBeforeTrailingLambda:
      active: false

    Wrapping:
      active: true
      
      indentSize: 4
    SortRule:
      active: true
